### ISSUE TITLE
Segfault in docker container

### ISSUE THREAD

**Issue by dhaeckel** [code-lts/welcome#7]
Hi all,

I created a docker container to profile a php project (running on WSL2). I'm sporadically getting the follwoing errors from apache:
```
172.25.0.1 - - [23/Aug/2021:09:04:37 +0000] "GET / HTTP/1.1" 503 299
[Mon Aug 23 09:04:37.872704 2021] [proxy_fcgi:error] [pid 93:tid 140086196827904] [client 172.25.0.1:33434] AH01067: Failed to read FastCGI header, referer: http://localhost:8090/
[Mon Aug 23 09:04:37.872784 2021] [proxy_fcgi:error] [pid 93:tid 140086196827904] (104)Connection reset by peer: [client 172.25.0.1:33434] AH01075: Error dispatching request to :8090: , referer: http://localhost:8090/
```
I traced it back to the php-fpm container, there I see this:
```
[23-Aug-2021 09:04:37] WARNING: [pool www] child 184 exited on signal 11 (SIGSEGV) after 2.944103 seconds from start
```
I then performed dmesg | grep segfault | tail -10 ,  which resulted in:
```
[162378.980332] php-fpm[21215]: segfault at 7f7324d61f64 ip 00007f732f5c2bc3 sp 00007ffcb35ec5a0 error 4 in xhprof.so[7f732f5c0000+3000]
```

**Comment by williamdes** [comment]
Hi @dhaeckel 
I will try to help you but I am not linked to the xhprof project in any ways

Could you share your docker-compose file ?
Or docker setup ?

**Comment by dhaeckel** [comment]
Hi @williamdes,

thaks for your help, here is my dockerfile

```dockerfile
FROM php:7.4.20-fpm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    procps

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    sync && \
    install-php-extensions \
        apcu \
        bcmath \
        bz2 \
        calendar \
        csv \
        exif \
        gd \
        gettext \
        gmp \
        http \
        imagick \
        imap \
        intl \
        ldap \
        mcrypt \
        mysqli \
        pcntl \
        pdo_mysql \
        pspell \
        raphf \
        shmop \
        snmp \
        soap \
        sockets \
        sysvmsg \
        sysvsem \
        sysvshm \
        xhprof \
        xmlrpc \
        xsl \
        opcache \
        zip

COPY php.ini $PHP_INI_DIR
```
changed ini settings:
```ini
short_open_tag = On
[xhprof]
xhprof.output_dir = /usr/local/apache2/htdocs/logs

[apcu]
apc.mmap_file_mask = /tmp/apc.XXXXXX
```

**Comment by williamdes** [comment]
Hi @dhaeckel

You'd probably better `apt install pecl`
And then `pecl install xhprof`


But my recommendation you be to use php 8 if possible
The extension has segfaults when you submit some kind of multi part form https://github.com/phpmyadmin/phpmyadmin/issues/16885

**Comment by dhaeckel** [comment]
Hi @williamdes,

thanks for the tip, but I am locked to php7.4 so changeing to 8 is not posssible atm. Using pecl for installing did not change the behaviour unfortunately. I checked out the linked issue, but I am not using multipart upload, I am profiling REST api endpoints and some long running php processes. I'll try to do some more testing and see if Ican get around this issue.

**Comment by williamdes** [comment]
> Hi @williamdes,
> 
> thanks for the tip, but I am locked to php7.4 so changeing to 8 is not posssible atm. Using pecl for installing did not change the behaviour unfortunately. I checked out the linked issue, but I am not using multipart upload, I am profiling REST api endpoints and some long running php processes. I'll try to do some more testing and see if Ican get around this issue.

Uh, if you mange to someway have php debug tools and print a trace it can probably be interesting to find out

**Comment by dhaeckel** [comment]
Hi @williamdes,

I'll try and debug it in the coming days. Do you want to continue here then, or should I open a new issue when I find out something over at the xhprof repo?

**Comment by williamdes** [comment]
> The extension has segfaults

Oh, I got confused, forget my link this is not the same pecl extension

> I'll try and debug it in the coming days. Do you want to continue here then, or should I open a new issue when I find out something over at the xhprof repo?

Yeah maybe open an issue at https://github.com/longxinH/xhprof

**Comment by dhaeckel** [comment]
Alright, I will close this issue and open one over at https://github.com/longxinH/xhprof. Thanks for your effort 👍
